=== JaimeeCM/JaimeeCM.github.io/XML/DTD-XSD/Tarifas.dtd
<!ELEMENT tarifas (tarifa+)>
<!ELEMENT tarifa (tipo, duracion, informacion, activacion?, precio)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT informacion (#PCDATA)>
<!ELEMENT activacion (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

=== JaimeeCM/JaimeeCM.github.io/XML/XML/Tarifas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tarifas SYSTEM "../DTD-XSD/Tarifas.dtd">
<?xml-stylesheet type="html/xsl" href="../XSL/Tarifas.xsl"?>

<tarifas>
      <tarifa>
        <tipo>Mensual</tipo>
        <duracion>1 mes</duracion>
        <informacion>Al darte de alta la primera vez, tendrás que abonar una pulsera electrónica de
        acceso valorada en 19,90€. Cuídala, te valdrá para siempre que vengas y con ella tendrás acceso a otros centros
        Fit Vibe</informacion>
        <activacion>39,80 euros</activacion>
        <precio>31,90 euros</precio>
     </tarifa>
     <tarifa>
        <tipo>Trimestral</tipo>
        <duracion>3 meses</duracion>
        <informacion>Al darte de alta la primera vez, tendrás que abonar una pulsera electrónica de
        acceso valorada en 19,90€. Cuídala, te valdrá para siempre que vengas y con ella tendrás acceso a otros centros
        Fit Vibe</informacion>
        <activacion>19,90 euros</activacion>
        <precio>81 euros</precio>
     </tarifa>
     <tarifa>
        <tipo>Anual</tipo>
        <duracion>1 año</duracion>
        <informacion>Al darte de alta la primera vez, tendrás que abonar una pulsera electrónica de
        acceso valorada en 19,90€. Cuídala, te valdrá para siempre que vengas y con ella tendrás acceso a otros centros
        Fit Vibe</informacion>
        <activacion>Sin activacion</activacion>
        <precio>288 euros</precio>
     </tarifa>
</tarifas>
